AssertionError: wrong number of args

