assert() failed in "tests/delete_at_exit_error.oomph", line N
Program 'tests/.oomph-cache/delete_at_exit_error_compilation0/delete_at_exit_error' exited with status 1
assert() failed in "self_hosted/main.oomph", line N
