find_last: item not found
Program 'tests/.oomph-cache/find_last_error_compilation0/find_last_error' exited with status 1
assert() failed in "self_hosted/main.oomph", line N
