Error: null.get() was called
Program 'tests/.oomph-cache/null_get_error_compilation0/null_get_error' exited with status 1
assert() failed in "self_hosted/main.oomph", line N
